server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-registration
    username: root
    password: root@123$
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    show-sql: TRUE
    hibernate:
      ddl-auto: update